[package]
name = "tnn"
version = "0.1.0"
edition = "2021"
authors = ["Telenor"]
description = "A quality of life developer tool to interact with Telenor services"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["state", "extension", "extension_repository", "extensions/*"]

[dependencies]
extension = { path = "extension" }
extension_repository = { path = "extension_repository" }
extension_loader = { path = "extension_loader" }
logs = { path = "logs" }
tokio = { version = "1.32.0", features = ["full"] }
anyhow = "1.0.75"
