[package]
name = "tnn"
version = "0.1.0"
edition = "2021"
authors = ["Telenor"]
description = "A quality of life developer tool to interact with Telenor services"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
	"state",
	"extension",
	"extension_repository",
	"core",
	"builtin_extensions/marketplace/ext",
]

[dependencies]
ext_tnn = { path = "extension" }
tnn_core = { path = "core" }
util_tnn_repo = { path = "extension_repository" }
util_tnn_ext_loader = { path = "extension_loader" }
util_tnn_logs = { path = "logs" }

tokio = { version = "1.32.0", features = ["full"] }
anyhow = "1.0.75"
thiserror = "1.0.48"
clap = { version = "4.4.4", features = ["derive"] }
